import os, re
templates_dir = 'md-templates'

# Mapping of weird placeholders to standard ones
REPLACEMENTS = {
    # Projects / Products
    'YOUR_PRODUCT_1': 'YOUR_PROJECT_1',
    'YOUR_PRODUCT_2': 'YOUR_PROJECT_2',
    'YOUR_PRODUCT_3': 'YOUR_PROJECT_3',
    'YOUR_PRODUCT_1_URL': 'YOUR_PROJECT_1_DEMO',
    'YOUR_PRODUCT_2_URL': 'YOUR_PROJECT_2_DEMO',
    'YOUR_PRODUCT_3_URL': 'YOUR_PROJECT_3_DEMO',
    'YOUR_OSS_PROJECT_1': 'YOUR_PROJECT_1',
    'YOUR_OSS_PROJECT_2': 'YOUR_PROJECT_2',
    'YOUR_OSS_PROJECT_3': 'YOUR_PROJECT_3',
    'YOUR_GAME_1': 'YOUR_PROJECT_1',
    'YOUR_GAME_2': 'YOUR_PROJECT_2',
    'YOUR_CLIENT_1': 'YOUR_PROJECT_1',
    'YOUR_CLIENT_2': 'YOUR_PROJECT_2',
    'YOUR_CLIENT_3': 'YOUR_PROJECT_3',
    'YOUR_CONTRACT_1': 'YOUR_PROJECT_1',
    'YOUR_CONTRACT_2': 'YOUR_PROJECT_2',
    'YOUR_ARTICLE_1': 'YOUR_PROJECT_1',
    'YOUR_ARTICLE_1_URL': 'YOUR_PROJECT_1_DEMO',
    'YOUR_PAPER_1': 'YOUR_PROJECT_1',
    'YOUR_PAPER_1_URL': 'YOUR_PROJECT_1_DEMO',
    'YOUR_PAPER_2': 'YOUR_PROJECT_2',
    'YOUR_PAPER_2_URL': 'YOUR_PROJECT_2_DEMO',
    'YOUR_NOTEBOOK_1': 'YOUR_PROJECT_1',
    'YOUR_NOTEBOOK_2': 'YOUR_PROJECT_2',
    'YOUR_NB_1': 'YOUR_PROJECT_1',
    'YOUR_NB_2': 'YOUR_PROJECT_2',
    'YOUR_NLP_PROJECT_1': 'YOUR_PROJECT_1',
    'YOUR_NLP_PROJECT_2': 'YOUR_PROJECT_2',
    'YOUR_DESIGN_1': 'YOUR_PROJECT_1',
    'YOUR_DESIGN_2': 'YOUR_PROJECT_2',
    'YOUR_DESIGN_3': 'YOUR_PROJECT_3',
    'YOUR_FIGMA_1': 'YOUR_PROJECT_1_DEMO',
    'YOUR_COLLECTION_1': 'YOUR_PROJECT_1',
    'YOUR_COLLECTION_2': 'YOUR_PROJECT_2',
    'YOUR_THREAD_1': 'YOUR_PROJECT_1',
    'YOUR_VIDEO_1': 'YOUR_PROJECT_1',
    'YOUR_VIDEO_1_URL': 'YOUR_PROJECT_1_DEMO',
    
    # Achievements / Metrics
    'YOUR_12M_MRR': 'YOUR_ACHIEVEMENT_1',
    'YOUR_3M_MRR': 'YOUR_ACHIEVEMENT_2',
    'YOUR_6M_MRR': 'YOUR_ACHIEVEMENT_3',
    'YOUR_MRR': 'YOUR_ACHIEVEMENT_1',
    'YOUR_MRR_1': 'YOUR_ACHIEVEMENT_1',
    'YOUR_MRR_2': 'YOUR_ACHIEVEMENT_2',
    'YOUR_CURRENT_MRR': 'YOUR_ACHIEVEMENT_1',
    'YOUR_APP_DOWNLOADS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_CLIENT_COUNT': 'YOUR_ACHIEVEMENT_2',
    'YOUR_PRODUCT_COUNT': 'YOUR_ACHIEVEMENT_1',
    'YOUR_WIN_COUNT': 'YOUR_ACHIEVEMENT_1',
    'YOUR_HACKATHON_WINS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_HACKATHON_1': 'YOUR_ACHIEVEMENT_1',
    'YOUR_HACKATHON_2': 'YOUR_ACHIEVEMENT_2',
    'YOUR_HACKATHON_3': 'YOUR_ACHIEVEMENT_3',
    'YOUR_HACKATHON_4': 'YOUR_ACHIEVEMENT_4',
    'YOUR_PRIZE_1': 'YOUR_ACHIEVEMENT_1',
    'YOUR_PRIZE_2': 'YOUR_ACHIEVEMENT_2',
    'YOUR_PRIZE_3': 'YOUR_ACHIEVEMENT_3',
    'YOUR_PRIZE_4': 'YOUR_ACHIEVEMENT_4',
    'YOUR_CONF_1': 'YOUR_ACHIEVEMENT_1',
    'YOUR_CONF_2': 'YOUR_ACHIEVEMENT_2',
    'YOUR_VENUE_1': 'YOUR_ACHIEVEMENT_1',
    'YOUR_VENUE_2': 'YOUR_ACHIEVEMENT_2',
    'YOUR_REVENUE': 'YOUR_ACHIEVEMENT_1',
    'YOUR_PROMOTIONS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_REPORTS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_READS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_VIEWS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_IMPRESSIONS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_SUBS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_SUBSCRIBERS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_FOLLOWERS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_TOTAL_COMMITS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_TOTAL_PRS': 'YOUR_ACHIEVEMENT_2',
    'YOUR_PRS_COUNT': 'YOUR_ACHIEVEMENT_1',
    'YOUR_CVE_COUNT': 'YOUR_ACHIEVEMENT_1',
    'YOUR_MENTEE_COUNT': 'YOUR_ACHIEVEMENT_1',
    'YOUR_BLOG_COUNT': 'YOUR_ACHIEVEMENT_1',
    'YOUR_COUNT': 'YOUR_ACHIEVEMENT_1',
    'YOUR_PERF_GAIN': 'YOUR_ACHIEVEMENT_1',
    'YOUR_RANK': 'YOUR_ACHIEVEMENT_1',
    'YOUR_RATING': 'YOUR_ACHIEVEMENT_2',

    # Descriptions / Text
    'YOUR_DESC_1': 'YOUR_PROJECT_1_DESC',
    'YOUR_DESC_2': 'YOUR_PROJECT_2_DESC',
    'YOUR_DESC_3': 'YOUR_PROJECT_3_DESC',
    'YOUR_DESC_4': 'YOUR_PROJECT_4_DESC',
    'YOUR_TAGLINE_1': 'YOUR_TAGLINE',
    'YOUR_TAGLINE_2': 'YOUR_FOCUS',
    'YOUR_PROFESSIONAL_SUMMARY': 'YOUR_BIO',
    'YOUR_LEADERSHIP_QUOTE': 'YOUR_QUOTE',
    'YOUR_LEADERSHIP_PRINCIPLE_1': 'YOUR_FUN_FACT_1',
    'YOUR_LEADERSHIP_PRINCIPLE_2': 'YOUR_FUN_FACT_2',
    'YOUR_LEADERSHIP_PRINCIPLE_3': 'YOUR_FUN_FACT_3',
    'YOUR_SPECIALTY': 'YOUR_FOCUS',
    'YOUR_SUBJECT': 'YOUR_FOCUS',
    'YOUR_GENRE': 'YOUR_FOCUS',
    'YOUR_ENGINE': 'YOUR_TOOLS',
    'YOUR_PLATFORM': 'YOUR_TOOLS',
    'YOUR_PLAYERS': 'YOUR_ACHIEVEMENT_1',
    'YOUR_COMMUNITY_NAME': 'YOUR_COMPANY',
    'YOUR_PREV_COMPANY': 'YOUR_COMPANY',
    'YOUR_INSTITUTION': 'YOUR_UNIVERSITY',
    'YOUR_PROGRAM': 'YOUR_MAJOR',
    'YOUR_DEGREE': 'YOUR_MAJOR',
    'YOUR_MODULE': 'YOUR_CURRENTLY_LEARNING',
    'YOUR_COURSE': 'YOUR_CURRENTLY_LEARNING',

    # Skills
    'YOUR_SKILL_1': 'YOUR_TECH_1',
    'YOUR_SKILL_2': 'YOUR_TECH_2',
    'YOUR_DATA_1': 'YOUR_TECH_1',
    'YOUR_DATA_2': 'YOUR_TECH_2',
    'YOUR_LANGUAGES': 'YOUR_TOPICS',
    'YOUR_FRAMEWORKS': 'YOUR_TOOLS',
    'YOUR_DATABASES': 'YOUR_TOOLS',
    'YOUR_LANGUAGE': 'YOUR_TECH_1',

    # Misc
    'YOUR_AGE': 'YOUR_YEARS',
    'YOUR_HOBBY_1': 'YOUR_FUN_FACT_1',
    'YOUR_HOBBY_2': 'YOUR_FUN_FACT_2',
    'YOUR_INTEREST_1': 'YOUR_FUN_FACT_1',
    'YOUR_INTEREST_2': 'YOUR_FUN_FACT_2',
    'YOUR_INTEREST_3': 'YOUR_FUN_FACT_3',
    'YOUR_INTEREST_4': 'YOUR_FUN_FACT_4',
    'YOUR_COLLAB': 'YOUR_PROJECT',
    'YOUR_FIX': 'YOUR_PROJECT',
    'YOUR_FEATURE': 'YOUR_PROJECT',
}

gif_injected = 0
for filename in os.listdir(templates_dir):
    if not filename.endswith(".md"):
        continue
    filepath = os.path.join(templates_dir, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    
    new_content = content
    for old, new in REPLACEMENTS.items():
        new_content = re.sub(r"\b" + old + r"\b", new, new_content)
    
    # Add a GIF placeholder at the top if it is not a plain simple one, or just add one generally
    if "YOUR_GIF" not in new_content and "animated" in filename:
        new_content = f"<div align=\"center\">\n  <img src=\"YOUR_GIF_1\" width=\"100%\" />\n</div>\n\n{new_content}"
        gif_injected += 1
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(new_content)

print(f"Replaced custom placeholders in md-templates and injected gifs into {gif_injected} templates.")
