/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserDatailsRouteImport } from './routes/user-datails'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as RepoReadmeRouteImport } from './routes/repo-readme'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as IndexRouteImport } from './routes/index'

const UserDatailsRoute = UserDatailsRouteImport.update({
  id: '/user-datails',
  path: '/user-datails',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoReadmeRoute = RepoReadmeRouteImport.update({
  id: '/repo-readme',
  path: '/repo-readme',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/repo-readme': typeof RepoReadmeRoute
  '/templates': typeof TemplatesRoute
  '/user-datails': typeof UserDatailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/repo-readme': typeof RepoReadmeRoute
  '/templates': typeof TemplatesRoute
  '/user-datails': typeof UserDatailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/repo-readme': typeof RepoReadmeRoute
  '/templates': typeof TemplatesRoute
  '/user-datails': typeof UserDatailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generator'
    | '/repo-readme'
    | '/templates'
    | '/user-datails'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generator' | '/repo-readme' | '/templates' | '/user-datails'
  id:
    | '__root__'
    | '/'
    | '/generator'
    | '/repo-readme'
    | '/templates'
    | '/user-datails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneratorRoute: typeof GeneratorRoute
  RepoReadmeRoute: typeof RepoReadmeRoute
  TemplatesRoute: typeof TemplatesRoute
  UserDatailsRoute: typeof UserDatailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-datails': {
      id: '/user-datails'
      path: '/user-datails'
      fullPath: '/user-datails'
      preLoaderRoute: typeof UserDatailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo-readme': {
      id: '/repo-readme'
      path: '/repo-readme'
      fullPath: '/repo-readme'
      preLoaderRoute: typeof RepoReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneratorRoute: GeneratorRoute,
  RepoReadmeRoute: RepoReadmeRoute,
  TemplatesRoute: TemplatesRoute,
  UserDatailsRoute: UserDatailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
