/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserDetailsRouteImport } from './routes/user-details'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as RepoReadmeRouteImport } from './routes/repo-readme'
import { Route as ProfileReadmeRouteImport } from './routes/profile-readme'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as IndexRouteImport } from './routes/index'

const UserDetailsRoute = UserDetailsRouteImport.update({
  id: '/user-details',
  path: '/user-details',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoReadmeRoute = RepoReadmeRouteImport.update({
  id: '/repo-readme',
  path: '/repo-readme',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileReadmeRoute = ProfileReadmeRouteImport.update({
  id: '/profile-readme',
  path: '/profile-readme',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/profile-readme': typeof ProfileReadmeRoute
  '/repo-readme': typeof RepoReadmeRoute
  '/templates': typeof TemplatesRoute
  '/user-details': typeof UserDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/profile-readme': typeof ProfileReadmeRoute
  '/repo-readme': typeof RepoReadmeRoute
  '/templates': typeof TemplatesRoute
  '/user-details': typeof UserDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/profile-readme': typeof ProfileReadmeRoute
  '/repo-readme': typeof RepoReadmeRoute
  '/templates': typeof TemplatesRoute
  '/user-details': typeof UserDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generator'
    | '/profile-readme'
    | '/repo-readme'
    | '/templates'
    | '/user-details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generator'
    | '/profile-readme'
    | '/repo-readme'
    | '/templates'
    | '/user-details'
  id:
    | '__root__'
    | '/'
    | '/generator'
    | '/profile-readme'
    | '/repo-readme'
    | '/templates'
    | '/user-details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneratorRoute: typeof GeneratorRoute
  ProfileReadmeRoute: typeof ProfileReadmeRoute
  RepoReadmeRoute: typeof RepoReadmeRoute
  TemplatesRoute: typeof TemplatesRoute
  UserDetailsRoute: typeof UserDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-details': {
      id: '/user-details'
      path: '/user-details'
      fullPath: '/user-details'
      preLoaderRoute: typeof UserDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo-readme': {
      id: '/repo-readme'
      path: '/repo-readme'
      fullPath: '/repo-readme'
      preLoaderRoute: typeof RepoReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-readme': {
      id: '/profile-readme'
      path: '/profile-readme'
      fullPath: '/profile-readme'
      preLoaderRoute: typeof ProfileReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneratorRoute: GeneratorRoute,
  ProfileReadmeRoute: ProfileReadmeRoute,
  RepoReadmeRoute: RepoReadmeRoute,
  TemplatesRoute: TemplatesRoute,
  UserDetailsRoute: UserDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
